CREATE TABLE sales_data_sample (
    ORDERNUMBER INTEGER,
    QUANTITYORDERED INTEGER,
    PRICEEACH NUMERIC(12,2),
    ORDERLINENUMBER INTEGER,
    SALES NUMERIC(12,2),
    ORDERDATE VARCHAR(255),
    STATUS VARCHAR(255),
    QTR_ID INTEGER,
    MONTH_ID INTEGER,
    YEAR_ID INTEGER,
    PRODUCTLINE VARCHAR(255),
    MSRP INTEGER,
    PRODUCTCODE VARCHAR(255),
    CUSTOMERNAME VARCHAR(255),
    PHONE VARCHAR(255),
    ADDRESSLINE1 VARCHAR(255),
    ADDRESSLINE2 VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    POSTALCODE VARCHAR(255),
    COUNTRY VARCHAR(255),
    TERRITORY VARCHAR(255),
    CONTACTLASTNAME VARCHAR(255),
    CONTACTFIRSTNAME VARCHAR(255),
    DEALSIZE VARCHAR(255)
);

-- Example COPY command:
COPY sales_data_sample FROM '/path/to/sales_data_sample.csv' CSV HEADER DELIMITER ',';